### ISSUE TITLE
Livemap map does not show up.

### ISSUE THREAD

**Issue by NicholasS-dev** [AwesomeCore1/live-map#3]
the map does not load on the website. player makers work and all that. just the background image does not,

**Comment by KoenTech** [comment]
I have the same issue. @AwesomeCore1 When do you think you can fix this?

**Comment by NicholasS-dev** [comment]
I just resolved it myself actully, had to edit the code and change the source map link

**Comment by AwesomeCore1** [comment]
Hmm, weird. It worked for me the last time I checked it. The image host seems to be online still, I will look into it a bit further but thanks for lettings me know. Glad you fixed it yourself!

**Comment by AwesomeCore1** [comment]
The link to the original file seems to be working, can you share some more details regarding the issue? Like the OS, FiveM version, etc
